-- ════════════════════════════════════════════════════════════════════════════
--  HELLO MOVING — MySQL schema  (cPanel migration — self-hosted database)
--
--  Import via: cPanel → phpMyAdmin → (select your DB) → Import → choose this file
--  OR:         mysql -u <user> -p <db> < schema.mysql.sql
--
--  Engine: InnoDB · Charset: utf8mb4 (full Japanese + emoji support)
--  All UUID primary keys are generated by PHP (api/_lib.php uuid4()) on INSERT,
--  so no DB-side uuid() default is required (works on MySQL 5.7 + MariaDB 10.x).
-- ════════════════════════════════════════════════════════════════════════════

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ── hm_data : generic key-value CMS store (hero, faq, footer, prices, …) ──────
CREATE TABLE IF NOT EXISTS hm_data (
  id         CHAR(36)     NOT NULL,
  `key`      VARCHAR(191) NOT NULL,
  `value`    JSON         NOT NULL,
  updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY hm_data_key_unique (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── bookings ─────────────────────────────────────────────────────────────────
--  Column set matches the LIVE (drift-reconciled) schema that both the
--  public booking form (bookingService.js) and the admin Adapter write/read.
--  The HM-xxx reference + from/to/time/service are packed inside `notes`.
CREATE TABLE IF NOT EXISTS bookings (
  id             CHAR(36)     NOT NULL,
  customer_name  TEXT,
  customer_email VARCHAR(255),
  customer_phone VARCHAR(60),
  booking_date   VARCHAR(40),
  service_id     VARCHAR(191),
  status         VARCHAR(20)  NOT NULL DEFAULT 'pending',
  notes          TEXT,
  items          JSON,
  created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY bookings_status_idx (status),
  KEY bookings_booking_date_idx (booking_date),
  KEY bookings_email_idx (customer_email),
  KEY bookings_created_at_idx (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── calendar_availability : stores ONLY non-available dates ──────────────────
CREATE TABLE IF NOT EXISTS calendar_availability (
  id         CHAR(36)    NOT NULL,
  `date`     VARCHAR(40) NOT NULL,
  status     VARCHAR(20) NOT NULL DEFAULT 'full',
  updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY calendar_date_unique (`date`),
  KEY calendar_status_idx (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── reviews ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reviews (
  id                CHAR(36)     NOT NULL,
  reference_id      VARCHAR(191) NOT NULL,
  customer_name     TEXT,
  rating            TINYINT,
  review_text       TEXT,
  approved          TINYINT(1)   NOT NULL DEFAULT 0,
  published         TINYINT(1)   NOT NULL DEFAULT 0,
  headline          TEXT,
  service           VARCHAR(191),
  date_label        VARCHAR(80),
  location          VARCHAR(120),
  source            VARCHAR(20)  NOT NULL DEFAULT 'admin',
  booking_reference VARCHAR(191),
  created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY reviews_reference_id_unique (reference_id),
  KEY reviews_created_at_idx (created_at),
  KEY reviews_approved_idx (approved, published)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── services ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS services (
  id            CHAR(36)     NOT NULL,
  reference_id  VARCHAR(191) NOT NULL,
  title         TEXT,
  description   TEXT,
  display_order SMALLINT     NOT NULL DEFAULT 0,
  active        TINYINT(1)   NOT NULL DEFAULT 1,
  badge         VARCHAR(120),
  cta_text      VARCHAR(120),
  PRIMARY KEY (id),
  UNIQUE KEY services_reference_id_unique (reference_id),
  KEY services_order_idx (display_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── communications : admin ↔ customer message log (+ email delivery status) ──
CREATE TABLE IF NOT EXISTS communications (
  id             BIGINT       NOT NULL AUTO_INCREMENT,
  booking_id     VARCHAR(191),
  customer_email VARCHAR(255),
  sender_email   VARCHAR(255) NOT NULL DEFAULT 'booking@hello-moving.com',
  subject        TEXT,
  message        TEXT         NOT NULL,
  direction      VARCHAR(12)  NOT NULL DEFAULT 'outbound',
  created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by     VARCHAR(191),
  email_status   VARCHAR(12)  DEFAULT 'pending',
  email_error    TEXT,
  sent_at        DATETIME     NULL,
  PRIMARY KEY (id),
  KEY idx_comm_booking_id (booking_id),
  KEY idx_comm_customer_email (customer_email),
  KEY idx_comm_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── inbox_messages : inbound email (webhook target) ──────────────────────────
CREATE TABLE IF NOT EXISTS inbox_messages (
  id         CHAR(36)     NOT NULL,
  sender     TEXT         NOT NULL,
  email      VARCHAR(255) NOT NULL,
  subject    TEXT         NOT NULL,
  body       TEXT         NOT NULL,
  booking_id VARCHAR(191),
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_inbox_created_at (created_at),
  KEY idx_inbox_booking_id (booking_id),
  KEY idx_inbox_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ── audit_log : append-only action trail ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
  id          CHAR(36)     NOT NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor       VARCHAR(191) NOT NULL DEFAULT 'system',
  action      VARCHAR(40)  NOT NULL DEFAULT 'other',
  target_type VARCHAR(40)  NOT NULL DEFAULT '-',
  target_id   VARCHAR(191) NOT NULL DEFAULT '',
  details     TEXT,
  PRIMARY KEY (id),
  KEY idx_audit_created_at (created_at),
  KEY idx_audit_action (action),
  KEY idx_audit_target (target_type, target_id),
  KEY idx_audit_actor (actor)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;

-- ════════════════════════════════════════════════════════════════════════════
--  SEED  — services + a few approved reviews so the public site shows content
--          on a fresh database. (hm_data keys are optional: the JS Adapter has
--          built-in defaults for hero/faq/footer/prices/etc.)
--  UUIDs below are fixed constants so re-import is idempotent.
-- ════════════════════════════════════════════════════════════════════════════
INSERT INTO services (id, reference_id, title, description, display_order, active, badge, cta_text) VALUES
 ('11111111-0000-4000-8000-0000000000s1','SVC-1','単身引越し','1人分の荷物に最適化。必要な分だけコンパクトに対応。',0,1,'人気サービス','無料お見積り →'),
 ('11111111-0000-4000-8000-0000000000s2','SVC-2','カップル・ご夫婦引越し','養生から家具配置まで。二人の新生活をスムーズに。',1,1,'人気サービス','無料お見積り →'),
 ('11111111-0000-4000-8000-0000000000s3','SVC-3','学生・新生活引越し','初めての引越しも段取りから設置まで対応。',2,1,'人気サービス','無料お見積り →'),
 ('11111111-0000-4000-8000-0000000000s4','SVC-4','当日・お急ぎ引越しプラン','急な引越しも当日対応。最短2時間でご返信します。',3,1,'緊急対応',''),
 ('11111111-0000-4000-8000-0000000000s5','SVC-5','不用品回収・処分','回収・処分・搬出まで一括。手続き不要。',4,1,'','無料お見積り →'),
 ('11111111-0000-4000-8000-0000000000s6','SVC-6','家具組立・分解','IKEA・大型家具の組立・分解に対応。',5,1,'','無料お見積り →')
ON DUPLICATE KEY UPDATE title=VALUES(title), description=VALUES(description),
  display_order=VALUES(display_order), active=VALUES(active), badge=VALUES(badge), cta_text=VALUES(cta_text);

INSERT INTO reviews (id, reference_id, customer_name, rating, review_text, approved, published, headline, service, date_label, location, source) VALUES
 ('22222222-0000-4000-8000-00000000rev1','REV-SEED-1','田中 美咲',5,'丁寧に対応していただき、引越しがスムーズに完了しました。スタッフの方々がとても親切で、大切な家具も傷一つなく運んでいただけました。また利用したいと思います。',1,1,'対応が丁寧で安心でした','単身引越し','2026年4月','渋谷区','admin'),
 ('22222222-0000-4000-8000-00000000rev2','REV-SEED-2','Kenji Tanaka',5,'Very professional service! They handled everything carefully and were perfectly on time. English support was excellent throughout. Highly recommended for expats moving in Tokyo.',1,1,'Excellent English support — highly recommended','カップル・ご夫婦引越し','2026年3月','港区','admin'),
 ('22222222-0000-4000-8000-00000000rev3','REV-SEED-3','山田 太郎',5,'急な引越しにも関わらず、当日対応していただきました。料金も明確で、追加費用なしで完了しました。対応の速さと丁寧さに大変満足しております。',1,1,'当日対応で本当に助かりました','当日・お急ぎ引越しプラン','2026年5月','新宿区','admin'),
 ('22222222-0000-4000-8000-00000000rev4','REV-SEED-4','鈴木 花子',5,'学生の一人暮らし引越しで利用しました。初めての引越しで不安でしたが、スタッフの方が丁寧に説明してくださり安心できました。料金もリーズナブルでした。',1,1,'初めての引越しも安心してお任せできました','学生・新生活引越し','2026年4月','豊島区','admin'),
 ('22222222-0000-4000-8000-00000000rev5','REV-SEED-5','佐藤 健太',5,'不用品の回収もまとめてお願いしました。引越しと同時に処分できたので非常に助かりました。対応が迅速で、見積もり通りの金額で完了しました。',1,1,'引越しと不用品回収を同時に対応','不用品回収・処分','2026年2月','世田谷区','admin')
ON DUPLICATE KEY UPDATE customer_name=VALUES(customer_name), rating=VALUES(rating), review_text=VALUES(review_text),
  approved=VALUES(approved), published=VALUES(published), headline=VALUES(headline), service=VALUES(service),
  date_label=VALUES(date_label), location=VALUES(location), source=VALUES(source);
